### ISSUE TITLE
README中使用方法错误

### ISSUE THREAD

**Issue by zaixi** [ShichaoMa/translate_html#1]
* demo1 显示找不到命令
* demo4 显示
```Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from translate import Translate
>>> t = Translate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/__init__.py", line 131, in __init__
    self.web_site = web_site.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
>>> 
```
或者
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from translate import Translate
>>> t = Translate("translate.google.cn")
>>> t.translate("name")
Traceback (most recent call last):
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/tools.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/__init__.py", line 117, in _translate
    return getattr(self, random.choice(self.web_site).strip())(src, proxies, src_template)
AttributeError: 'Translate' object has no attribute 'translate.google.cn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/__init__.py", line 110, in translate
    or self.proxy, src_template)
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/tools.py", line 30, in wrapper
    result = error_handler(func.__name__, count, e, *args, **kwargs)
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/__init__.py", line 87, in trans_error_handler
    self.logger.debug("Error in %s for retry %s times. Error: %s"%(func_name, retry_time, e))
AttributeError: 'Translate' object has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liyj/.local/lib/python3.5/site-packages/translate/__init__.py", line 112, in translate
    self.logger.error("Error in translate, finally, we could not get the translate result. src: %s, Error:  %s"%(
AttributeError: 'Translate' object has no attribute 'logger'
>>> 
```

**Comment by ShichaoMa** [comment]
@zaixi 感谢提出issue， demo1是没有问题，找不到命令可能是因为你python的可执行程序path没有加入windows环境变量中。demo4的确是因为最近代码变动没有及时更新README造成的
```
In [1]: from translate import Translate

In [2]: help(Translate)
```
可以看到
```
 |  __init__(self, web_site=None, proxy_list=None, proxy_auth=None, retry_times=10, translate_timeout=5, load_module=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
```
默认的第一个参数是web_site，默认值 为None， 导致了`AttributeError: 'NoneType' object has no attribute 'split'`
可以使用如下方式调用
```
In [4]: with Translate("google") as t:
   ...:     print(t.translate("my"))
```
现在已修复，并更新了README.md
请安装最新版本
`pip install translate-html==1.2.2`

**Comment by zaixi** [comment]
谢谢，demo4可以正常运行，demo1还是找不到命令，我是ubuntu16系统，用pip安装的`pip3 install translate-html==1.2.2`
```
 liyj@liyj-Lenovo  ~/pdf/translate_html/translate   master  python3 -m translate
/usr/bin/python3: No module named translate.__main__; 'translate' is a package and cannot be directly executed
```

**Comment by ShichaoMa** [comment]
@zaixi 找不到命令一般都是你的环境变量配置有问题，我找了一台ubuntu安装测试是没有任何问题的，
```
longen@ubuntu-94:~$ pip install translate-html==1.2.2
Collecting translate-html==1.2.2
  Downloading translate-html-1.2.2.tar.gz
Requirement already satisfied: requests in ./.pyenv/versions/3.6.0/lib/python3.6/site-packages (from translate-html==1.2.2)
Installing collected packages: translate-html
  Found existing installation: translate-html 1.2.0
    Uninstalling translate-html-1.2.0:
      Successfully uninstalled translate-html-1.2.0
  Running setup.py install for translate-html ... done
Successfully installed translate-html-1.2.2
pyenv: cannot rehash: /home/longen/.pyenv/shims/.pyenv-shim exists
longen@ubuntu-94:~$ tra
tracepath            tracepath6           traceroute6          traceroute6.iputils  translate            trap
longen@ubuntu-94:~$ translate -h
usage: translate [-h] [-ws WEB_SITE] [-pl PROXY_LIST] [-pa PROXY_AUTH]
                 [-rt RETRY_TIMES] [-tt TRANSLATE_TIMEOUT] [-lm LOAD_MODULE]
                 src [src ...]

positional arguments:
  src                   The html you want to translate.

optional arguments:
  -h, --help            show this help message and exit
  -ws WEB_SITE, --web-site WEB_SITE
                        Which site do you want to use for translating, split
                        by `,`?
  -pl PROXY_LIST, --proxy-list PROXY_LIST
                        The proxy.list contains proxy to use for translating.
                        default: ./proxy.list
  -pa PROXY_AUTH, --proxy-auth PROXY_AUTH
                        Proxy password if have. eg. user:password
  -rt RETRY_TIMES, --retry-times RETRY_TIMES
                        If translate failed retry times. default: 10
  -tt TRANSLATE_TIMEOUT, --translate-timeout TRANSLATE_TIMEOUT
                        Translate timeout. default: 5
  -lm LOAD_MODULE, --load-module LOAD_MODULE
                        The module contains custom web site functions which
                        may use for translate. eg: trans.qq
longen@ubuntu-94:~$
```

**Comment by ShichaoMa** [comment]
@zaixi 你可以使用pyenv安装一个新版本的pythony试试看

http://www.cnblogs.com/ningvsban/p/4384995.html
